### ISSUE TITLE
Propagation labels are not optional

### ISSUE THREAD

**Issue by fancybear-dev** [badarsebard/terraform-provider-xsoar#5]
Documenation says propagation labels are optional, but because of a bug - this is currently not the case. I created this ticket so if anyone else encounters this, they know we have this issue as well.

We currently just pass the "all" label by default, as we don't need the propagation labels in our integrations.

![image](https://user-images.githubusercontent.com/78414914/165300452-b7b55847-b29e-4c95-8e92-faf2d521ad0f.png)

**Comment by jrauen** [comment]
without the `Computed: true` option on the `propagation_labels` attribute the provider was unable to set the value received from the API in the state, creating the inconsistent result. please pull the latest commit and see if this resolves your issue.

**Comment by fancybear-dev** [comment]
Have confirmed just now, this fixes the bug we were having! Thanks for the quick response!

Thank you for the explanation for your fix as well, this helps me understand the issue and fix it myself in the future 😊. All this provider development in Go is still quite new for me...
